CURRENT_TIME_FROM_UTC = 0

TEST_TIME_FORMAT = '%Y-%m-%d %H:%M:%S'

HOUR_MINUTE_FORMAT = "%H:%M"

DAY_MONTH_HOUR_MINUTE_FORMAT = "%d %m %H:%M"

TIMESTAMP_FORMAT = "%d.%m.%Y_%H:%M:%S"

ONE_MINUTE_IN_SECONDS = 60

